site_name: CookieDocs
site_description: Create your documentation site in a few minutes
repo_url: https://github.com/charlstown/cookie-site.git

# Configuration
# Theme
theme:
  name: material
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  custom_dir: overrides
  static_templates:
    - 404.html
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.path # Path rendered on the upper side
    - navigation.tracking # URL in the address bar is automatically updated with the active anchor in the table of contents.
    - navigation.tabs # Top-level sections are rendered in a menu layer below the header for viewports above
    #- navigation.sections # top-level sections are rendered as groups in the sidebar for viewports above
    - navigation.tabs # Documents can be directly attached to sections
    - navigation.footer
    - navigation.top # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again
    #- toc.integrate # Table of contents is always rendered as part of the navigation sidebar on the left.
    - search.suggest
    - search.highlight
    - content.code.copy # Codeblocks
    - content.tabs.link
    - navigation.indexes # Documents attached to sections
  language: en

  # Color palette
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


# Sorting menu pages
nav:
    - Home: 'index.md'
    - User Guide:
      - Getting Started: 'user-guide/getting-started.md'
      - Set Up: 'user-guide/set-up.md'
      - Usage: 'user-guide/usage.md'
      - Help wanted: 'user-guide/help.md'
    - Dev Guide:
      - Contribute: 'dev-guide/contribute.md'
      - CI CD: 'dev-guide/ci-cd.md'
    - About:
      - License: 'about/license.md'
      - External links: 'about/external-links.md'


# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition            # Block elements
  - pymdownx.details      # Collapsible call-outs
  - pymdownx.superfences  # Nested elements
  - pymdownx.mark         # Hihlighting text
  - attr_list             # To add buttons
  - md_in_html            # To add html in markdown (centred images)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# Plugins
plugins:
  - search
  - markdownextradata

  # css
extra_css:
  - assets/stylesheets/extra.css

# javascript
extra_javascript:
  - assets/javascripts/extra.js

# Copyright message
copyright: Copyright &copy; batcueva - 2023