site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.project_description }}
repo_url: {{ cookiecutter.repository_url }}
site_author: {{ cookiecutter.author }}

# Configuration
# Theme
theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight 
  language: en

  # Color palette
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: {{ cookiecutter.base_color }}
      accent: {{ 'teal' if cookiecutter.base_color == 'blue grey' else cookiecutter.base_color }}
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: {{ cookiecutter.base_color }}
      accent: {{ 'teal' if cookiecutter.base_color == 'blue grey' else cookiecutter.base_color }}
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


# Sorting menu pages
nav:
    - Home: 'index.md'
    - Getting started: 'getting-started.md' # getting started
    - About:
      - License: 'about/license.md'
      - External links: 'about/external-links.md'
      - Changelog: 'about/changelog.md'


# Extensions
markdown_extensions:
  - admonition            # Block elements
  - pymdownx.details      # Collapsible call-outs
  - pymdownx.superfences  # Nested elements
  - pymdownx.mark         # Hihlighting text
  - attr_list             # To add buttons
  - md_in_html            # To add html in markdown (centred images)
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search
  - markdownextradata
# css
extra_css:
  - assets/stylesheets/extra.css

# javascript
extra_javascript:
  - assets/javascripts/extra.js

# Copyright message
copyright: Copyright &copy; {{ cookiecutter.project_name}} - 2023

# Global variables
extra:
  links:
    self-host: 'url'
    learning-host: 'url'
