name: Label and assign issues when commented
on: 
  issue_comment:
    types: [created, edited]

jobs:
        
  label_issues:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Steps for /bloqued comment
      # Add bloqued label if commented
      - uses: actions/github-script@v7.0.1
        with:
          script: console.log(context)
      - uses: actions/github-script@v7.0.1
        if: contains(github.event.comment.body, '/bloqued')   # check the comment if it contains the keywords
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] bloqued"]
            })
      # Delete review label if change to bloqued
      - uses: actions/github-script@v7.0.1
        if: >
          contains(github.event.issue.labels.*.name, '[status] review') && 
          contains(github.event.comment.body, '/bloqued')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["[status] review"]
            })
      # Delete awaiting label if change to bloqued
      - uses: actions/github-script@v7.0.1
        if: >
          contains(github.event.comment.body, '/bloqued') &&
          contains(github.event.issue.labels.*.name, '[status] awaiting')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] awaiting"]
            })
      
      # Steps for /review comment
      # Add review label if commented
      - uses: actions/github-script@v7.0.1
        with:
          script: console.log(context)
      - uses: actions/github-script@v7.0.1
        if: contains(github.event.comment.body, '/review')   # check the comment if it contains the keywords
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] review"]
            })
      # Delete bloqued label if change to review
      - uses: actions/github-script@v7.0.1
        if: contains(github.event.comment.body, '/review')  && contains(github.event.issue.labels.*.name, '[status] bloqued')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] bloqued"]
            })
      # Delete awaiting label if change to review
      - uses: actions/github-script@v7.0.1
        if: >
          contains(github.event.comment.body, '/review') &&
          contains(github.event.issue.labels.*.name, '[status] awaiting')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] awaiting"]
            })

      # Steps for /awaiting or /await comment
      # Add awaiting label if commented
      - uses: actions/github-script@v7.0.1
        with:
          script: console.log(context)
      - uses: actions/github-script@v7.0.1
        if: >
          contains(github.event.comment.body, '/awaiting') ||
          contains(github.event.comment.body, '/await')
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] awaiting"]
            })
      # Delete review label if change to awaiting
      - uses: actions/github-script@v7.0.1
        if: >
          contains(github.event.comment.body, '/awaiting') ||
          contains(github.event.comment.body, '/await') &&
          contains(github.event.issue.labels.*.name, '[status] review')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] review"]
            })
      # Delete bloqued label if change to awaiting
      - uses: actions/github-script@v7.0.1
        if: >
          contains(github.event.comment.body, '/awaiting') ||
          contains(github.event.comment.body, '/await') &&
          contains(github.event.issue.labels.*.name, '[status] bloqued')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["[status] bloqued"]
            })
